# Generated by Django 2.2.2 on 2022-05-11 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_auto_20220511_1837'),
    ]

   
