# Generated by Django 2.2.2 on 2022-05-11 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_auto_20220511_1839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Municipio',
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
    ]
