# Generated by Django 2.2.2 on 2022-05-11 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_municipio_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Municipio'),
        ),
    ]
