# Generated by Django 2.2.2 on 2022-05-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_hotel_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='celular',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='eslogan',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
