# Generated by Django 2.2.2 on 2022-05-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0008_hotel_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/shows'),
        ),
    ]
