# Generated by Django 2.2.2 on 2022-05-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0010_config'),
    ]

    operations = [
       
    ]
