# Generated by Django 2.2.2 on 2022-05-13 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0011_hotel_expedido'),
    ]

    operations = [
      
    ]
