# Generated by Django 2.2.2 on 2022-05-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0012_remove_hotel_expedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='estrellas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
