# Generated by Django 2.2.2 on 2022-05-17 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0014_remove_hotel_expedido'),
    ]

    operations = [
      
    ]
