# Generated by Django 2.2.2 on 2022-05-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turista',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOLTERO(A)', 'SOLTERO(A)'), ('CASADO(A)', 'CASADO(A)'), ('VIUDO(A)', 'VIUDO(A)'), ('DIVORCIADO(A)', 'DIVORCIADO(A)')], max_length=50, null=True),
        ),
    ]
