# Generated by Django 2.2.2 on 2022-05-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_turista_estado_civil'),
    ]

    operations = [
        migrations.AddField(
            model_name='turista',
            name='expedido',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
