# Generated by Django 2.2.2 on 2022-05-17 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_turista_expedido'),
    ]

    operations = [       
        migrations.AddField(
            model_name='turistahotel',
            name='procedencia',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),        
    ]
