# Generated by Django 2.2.2 on 2022-05-17 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_auto_20220517_1813'),
    ]

    operations = [
       
    ]
