# Generated by Django 2.2.2 on 2022-05-17 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_auto_20220517_1815'),
    ]

    operations = [
       
    ]
