# Generated by Django 2.2.2 on 2022-05-17 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_auto_20220517_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='turista',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Pais'),
        ),
    ]
