# Generated by Django 2.2.2 on 2022-05-17 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0011_remove_turista_procedencia'),
    ]

    operations = [
       
    ]
