# Generated by Django 4.0.6 on 2022-09-28 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0012_remove_turista_procedencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turista',
            name='procedencia',
        ),
    ]
